# Generated by Django 5.2.6 on 2025-10-16 18:26

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter common name (e.g. Spider Plant, Snake Plant)', max_length=200, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='commonName_name_case_insensitive_unique', violation_error_message='Common name already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the plant's Location (e.g. Living Room, Kitchen, etc.)", max_length=50, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='location_name_case_insensitive_unique', violation_error_message='Location already exists (case insensitive match)')],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=200, unique=True)),
                ('water', models.CharField(choices=[('f', 'frequent'), ('r', 'regular'), ('i', 'infrequent')], help_text='watering frequency', max_length=1)),
                ('sun', models.CharField(choices=[('f', 'full sun'), ('fp', 'full sun to part shade'), ('p', 'part shade'), ('ps', 'part shade to full shade'), ('sh', 'full shade')], help_text='sun light preference', max_length=2)),
                ('description', models.TextField(help_text='Enter a brief description of the plant', max_length=1000)),
                ('care_tips', models.TextField(help_text='Enter a few care tips for the plant', max_length=1000)),
                ('common_name', models.ManyToManyField(help_text='Select a common name for this plant', to='nursery.commonname')),
            ],
        ),
        migrations.CreateModel(
            name='PlantInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular plant across whole nursery', primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=200, unique=True)),
                ('purchased', models.DateField(blank=True, null=True)),
                ('due_watered', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'purchased'), ('w', 'watered'), ('n', 'not watered')], default='p', help_text='plant watered status', max_length=1)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='nursery.location')),
                ('plant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='nursery.plant')),
            ],
            options={
                'ordering': ['due_watered'],
            },
        ),
    ]
